from_latest_tag = true
ignore_merge_commits = true
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_untracked = true
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"
skip_ci = "[skip ci]"

disable_changelog = true

[git_hooks]

[bump_profiles]

[packages]