name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DOCKER_IMAGE_NAME: "redbonzai/trending-hashtags-app"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.14.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'
      - run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4.2.2
      - run: npx nx run trending-hashtags-app:lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4.2.2
      - run: npx nx run trending-hashtags-app:test

  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: redbonzai/github-actions/cog-check@v0
        with:
          from-latest-tag: true
          ignore-merge-commits: true

  version:
    runs-on: ubuntu-latest
    needs: [check-commits]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: redbonzai/github-actions/setup-cocogitto@v1
        with:
          version: '6.1.0'
      - name: Generate Version
        run: |
          cog bump --auto

  build:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f Dockerfile .
      - name: Tag Docker Image
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:latest
